# ruff.toml
line-length = 100
target-version = "py312"

src = ["src", "tests"]

[lint]
select = ["E", "F", "I", "B", "UP"]
ignore = ["E501"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[lint.per-file-ignores]
"tests/**/*.py" = ["B011"]
